FROM nginx:alpine

COPY website/src /usr/share/nginx/html
COPY website/nginx.conf /etc/nginx/conf.d/default.conf

COPY website/entrypoint.sh /docker-entrypoint.d/entrypoint.sh
RUN chmod +x /docker-entrypoint.d/entrypoint.sh

EXPOSE 80

ENTRYPOINT ["/docker-entrypoint.d/entrypoint.sh"]
